### ISSUE TITLE
Add Email Form

### ISSUE THREAD

**Issue by BonfireScratch** [N-language/WebClient#2]
Stalpinth add a working email form

**Comment by BonfireScratch** [comment]
@Stalpinth add an email form

**Comment by Stalpinth** [comment]
The design?

**Comment by BonfireScratch** [comment]
@Stalpinth No, I will do the design. You do the scripting

**Comment by BonfireScratch** [comment]
@Stalpinth are you working on it?

**Comment by Stalpinth** [comment]
Yes.

**Comment by BonfireScratch** [comment]
@Stalpinth have you managed to do anything? Also, make the page www.nsharp-lang.com

**Comment by Stalpinth** [comment]
Yes, a bit. What should the email form do? The page... is that the website of N#?

**Comment by BonfireScratch** [comment]
Well, for now, I want you to have the user input an email and send him a confirmation email. And yes it will become the website of N#

**Comment by Stalpinth** [comment]
Ok. I *can* buy the website **and** do some things so it work (with GitHub Pages). For now, I'm working on the email form.

**Comment by BonfireScratch** [comment]
@Stalpinth have you considered using Ruby?

**Comment by Stalpinth** [comment]
I haven't used Ruby.

**Comment by BonfireScratch** [comment]
@Stalpinth what do you use really?

**Comment by Stalpinth** [comment]
I haven't started with the coding yet.

**Comment by BonfireScratch** [comment]
@Stalpinth what do you think you will use?

**Comment by Stalpinth** [comment]
I don't know lol

**Comment by BonfireScratch** [comment]
@apple502j can you help?

**Comment by BonfireScratch** [comment]
@N-language/webbackend have you found anything?

**Comment by BonfireScratch** [comment]
@apple502j @Stalpinth I found a way to do it with Python. First you must open an AWS (Amazon Web Services) account

**Comment by BonfireScratch** [comment]
@apple502j enable PHP
